# Generated by Django 3.2.11 on 2022-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzdata', '0024_remove_property_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Value'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Value'),
        ),
    ]
